eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eurekaserver/   #注明服务注册中心的地址
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVICE-RIBBON    #以 /api-a/ 开头的请求都转发给 SERVICE-RIBBON 服务
    api-b:
      path: /api-b/**
      serviceId: SERVICE-FEIGN   #以 /api-b/ 开头的请求都转发给 SERVICE-FEIGN 服务
server:
  port: 8769
spring:
  application:
    name: SERVICE-ZUUL    #服务与服务之间相互调用是通过这个 name
