server:
  port: 8767
spring:
  application:
    name: SERVICE-CONFIGSERVER    #服务与服务之间相互调用是通过这个 name
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yeta666/scl/   #git仓库地址
          search-paths: configs   #仓库路径
          username: 429721783@qq.com    #git用户名
          password: tt429721783   #git密码
      label: master   #仓库的分支
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eurekaserver/   #注明服务注册中心的地址


