eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eurekaserver/   #注明服务注册中心的地址
feign:
  hystrix:
    enabled: true   #开启熔断器
server:
  port: 8765
spring:
  application:
    name: SERVICE-FEIGN    #服务与服务之间相互调用是通过这个 name
